### ISSUE TITLE
iojs - Unexpected token ILLEGAL

### ISSUE THREAD

**Issue by dweinstein** [dchester/generator-async#1]
``` javascript
% iojs --harmony -e 'var async = require("generator-async"); var fs = async.require("fs");'
/Users/user/junk/generator-async/node_modules/generator-async/node_modules/module-async-mapper/node_modules/esprima/esprima.js:3718
            throw e;
                  ^
Error: Line 26: Unexpected token ILLEGAL
    at throwError (/Users/user/junk/generator-async/node_modules/generator-async/node_modules/module-async-mapper/node_modules/esprima/esprima.js:1836:21)
    at scanNumericLiteral (/Users/user/junk/generator-async/node_modules/generator-async/node_modules/module-async-mapper/node_modules/esprima/esprima.js:900:13)
    at advance (/Users/user/junk/generator-async/node_modules/generator-async/node_modules/module-async-mapper/node_modules/esprima/esprima.js:1311:20)
    at lex (/Users/user/junk/generator-async/node_modules/generator-async/node_modules/module-async-mapper/node_modules/esprima/esprima.js:1360:78)
    at expect (/Users/user/junk/generator-async/node_modules/generator-async/node_modules/module-async-mapper/node_modules/esprima/esprima.js:1896:21)
    at parseArguments (/Users/user/junk/generator-async/node_modules/generator-async/node_modules/module-async-mapper/node_modules/esprima/esprima.js:2217:17)
    at parseLeftHandSideExpressionAllowCall (/Users/user/junk/generator-async/node_modules/generator-async/node_modules/module-async-mapper/node_modules/esprima/esprima.js:2283:24)
    at parsePostfixExpression (/Users/user/junk/generator-async/node_modules/generator-async/node_modules/module-async-mapper/node_modules/esprima/esprima.js:2325:16)
    at parseUnaryExpression (/Users/user/junk/generator-async/node_modules/generator-async/node_modules/module-async-mapper/node_modules/esprima/esprima.js:2352:20)
    at parseBinaryExpression (/Users/user/junk/generator-async/node_modules/generator-async/node_modules/module-async-mapper/node_modules/esprima/esprima.js:2473:16)
```

**Comment by dweinstein** [comment]
I think this takes care of this one... https://github.com/dchester/module-async-mapper/pull/1

**Comment by dweinstein** [comment]
confirmed; I no longer get this error on iojs if the module-async-mapper is updated. will follow up with PR

**Comment by dweinstein** [comment]
:+1:
